[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
fix = false

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = ["B008", "E501"]

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_ignores = false
disallow_untyped_defs = false
ignore_missing_imports = true
allow_untyped_defs = true
allow_incomplete_defs = true
no_implicit_optional = false
ignore_errors = true
